class_name CinematicDefinition
extends Resource
## A cinematic: shots played one after another in place of a story card's words on black. Generated by
## tools/cinematics/build_cinematics.mjs into assets/cinematics/<id>/<id>.tres; read-only at runtime.

@export var id: StringName = &""
@export var shots: Array[CinematicShot] = []


## The cinematic made for a story card, or null when that card is still words on black.
static func find(card: StringName) -> CinematicDefinition:
	var path: String = "res://assets/cinematics/%s/%s.tres" % [card, card]
	if not ResourceLoader.exists(path):
		return null
	return load(path) as CinematicDefinition
